### PR TITLE
Bugfix / Make SearchExpression optional in SearchParameters

### LINKED ISSUE #107: It is not possible to search without a search expression
### Steps to Reproduce:
Write a search request without a search expression:

```
const searchRequest = trac.api.MetadataSearchRequest.create({
        tenant: tenant,
        searchParams: {
            searchAsOf: searchAsOf,
            objectType: trac.ObjectType.DATA
        }
    })
```

or

```
const searchRequest = trac.api.MetadataSearchRequest.create({
        tenant: tenant,
        searchParams: {
            searchAsOf: searchAsOf,
            objectType: trac.ObjectType.DATA,
            search: undefined
        }
    })
```

### Expected Result:
Without a search term the request should bring back a full list of objects without filtering applied.

### Actual Result:
The request errors.

### Environment:

`trac-web-api": "file:../../../../dev/trac/trac-web-api-0.3.1.tgz`

### PR DESCRIPTION
**Pull request by mslapek**
Fixes #107

### CODE REVIEW

File: tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataSearchApiTest.java [hunk 1]
```diff
@@ -567,30 +623,6 @@ void emptySearchResult() {
         assertEquals(0, searchResult.getSearchResultCount());
     }
 
-    @Test
-    void invalidSearch_nullParams() {
-
-        var searchRequest = MetadataSearchRequest.newBuilder()
```
Comment (martin-traverse) [inline tracdap-services/tracdap-svc-meta/src/test/java/org/finos/tracdap/svc/meta/api/MetadataSearchApiTest.java:573]: I think we want to keep the first half of this test? Just get rid of the second part?

**Comment by martin-traverse** [comment]
Looks good, one minor comment in the test code, I think it's still an error if the search params object is missing altogether.

**Comment by mslapek** [comment]
> Looks good, one minor comment in the test code, I think it's still an error if the search params object is missing altogether.

The issue #107 has provided `searchParams` in all examples.

**Review by martin-traverse — APPROVED** [review]
